# Generated by Django 4.2.2 on 2023-07-04 05:25

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('condominios', '0001_initial'),
    ]

    operations = [
        migrations.RenameField(
            model_name='departamento',
            old_name='nombre',
            new_name='nombreP',
        ),
    ]
